@startuml inventiveDB
left to right direction

entity users {
+id : int
--
username : string
password : string
role : enum('admin', 'normal')
createdAt : datetime
modifiedAt : datetime
lastAuthUpdate : datetime
}

entity inventories {
    +id : int
    +//userId// : int
    --
    inventory : string
    createdAt : datetime
    modifiedAt : datetime
}

entity products {
    +id : int
    +//inventoryId// : int
    --
    product : string
    description : string
    quantity : int
    createdAt : date
    modifiedAt : datetime
}

users ||--o{ inventories : own
inventories ||--o{ products : contain

@enduml
